import DropDown from "../../DropDown";

const Component = () => {
    return (
        <div>
            <h3>Code Syntax Highlighting Fixed</h3>
            <p>
                Previously I was using the following <a href="https://github.com/googlearchive/code-prettify">script</a> to
                do code syntax highlighting for me but I realized it was quite bad. I've decided to replace it with
                another method of formatting code, using html and css.
            </p>
            <p>
                After some searching I found the atom module <a href="https://atom.io/packages/copy-with-style">copy-with-style</a> which
                does exactly what I want. Sadly it doesn't work but looking at the pull requests there is a functioning version <a href="https://github.com/my-codeworks/copy-with-style/pull/16">here</a>.
            </p><br />
            <p>
                Next I created a script to remove the background and convert the HTML to JSX, the form that react webpages
                are written in. I did this in python using some regex to modify the HTML and then <b>selenium</b> to use and online
                converter so I don't have to try and do that myself. The full code is shown below:
            </p><br />
            <DropDown>
                <h5>CodeFormatter.py <i className="arrow down" style={{float: "right", marginRight: "10px"}} /></h5>
                <pre className="code"><code><span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> selenium </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> webdriver</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> selenium.webdriver.chrome.service </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> Service</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> webdriver_manager.chrome </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> ChromeDriverManager</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> selenium.webdriver.common.by </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> By</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> selenium.webdriver.common.keys </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> Keys</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>from</span><span style={{color: 'rgb(56, 58, 66)'}}> selenium.webdriver.common.action_chains </span><span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> ActionChains</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> pyperclip </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># for copying</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> sys</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> time</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> re</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>convertHTML</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>html</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>driver </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> webdriver.</span><span style={{color: 'rgb(64, 120, 242)'}}>Chrome</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>service</span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(64, 120, 242)'}}>Service</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(64, 120, 242)'}}>ChromeDriverManager</span><span style={{color: 'rgb(56, 58, 66)'}}>().</span><span style={{color: 'rgb(64, 120, 242)'}}>install</span><span style={{color: 'rgb(56, 58, 66)'}}>()))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>driver.</span><span style={{color: 'rgb(64, 120, 242)'}}>implicitly_wait</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>driver.</span><span style={{color: 'rgb(64, 120, 242)'}}>get</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"https://magic.reactjs.net/htmltojsx.htm"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>pyperclip.</span><span style={{color: 'rgb(64, 120, 242)'}}>copy</span><span style={{color: 'rgb(56, 58, 66)'}}>(html) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># copy html so it can be pasted</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(64, 120, 242)'}}>ActionChains</span><span style={{color: 'rgb(56, 58, 66)'}}>(driver).</span><span style={{color: 'rgb(64, 120, 242)'}}>send_keys</span><span style={{color: 'rgb(56, 58, 66)'}}>(Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>TAB</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>SPACE</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>TAB</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>DELETE</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>*</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>200</span><span style={{color: 'rgb(56, 58, 66)'}}>).</span><span style={{color: 'rgb(64, 120, 242)'}}>perform</span><span style={{color: 'rgb(56, 58, 66)'}}>()</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(64, 120, 242)'}}>ActionChains</span><span style={{color: 'rgb(56, 58, 66)'}}>(driver).</span><span style={{color: 'rgb(64, 120, 242)'}}>key_down</span><span style={{color: 'rgb(56, 58, 66)'}}>(Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>CONTROL</span><span style={{color: 'rgb(56, 58, 66)'}}>).</span><span style={{color: 'rgb(64, 120, 242)'}}>send_keys</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"v"</span><span style={{color: 'rgb(56, 58, 66)'}}>).</span><span style={{color: 'rgb(64, 120, 242)'}}>key_up</span><span style={{color: 'rgb(56, 58, 66)'}}>(Keys.</span><span style={{color: 'rgb(228, 86, 73)'}}>CONTROL</span><span style={{color: 'rgb(56, 58, 66)'}}>).</span><span style={{color: 'rgb(64, 120, 242)'}}>perform</span><span style={{color: 'rgb(56, 58, 66)'}}>() </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># paste html</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>time.</span><span style={{color: 'rgb(64, 120, 242)'}}>sleep</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># wait for conversion</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>output </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> driver.</span><span style={{color: 'rgb(64, 120, 242)'}}>find_elements</span><span style={{color: 'rgb(56, 58, 66)'}}>(By.</span><span style={{color: 'rgb(228, 86, 73)'}}>CLASS_NAME</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>"CodeMirror-code"</span><span style={{color: 'rgb(56, 58, 66)'}}>)[</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>].</span><span style={{color: 'rgb(64, 120, 242)'}}>get_attribute</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>'innerText'</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>output </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> output.</span><span style={{color: 'rgb(64, 120, 242)'}}>replace</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"&lt;span style={"{"}{"{"}display: 'inline-block'{"}"}{"}"} className=</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>line</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>&gt;"</span><span style={{color: 'rgb(56, 58, 66)'}}>,</span><span style={{color: 'rgb(80, 161, 79)'}}>"&lt;span style={"{"}{"{"}display: 'inline-block'{"}"}{"}"} className=</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>line</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>&gt;</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>driver.</span><span style={{color: 'rgb(64, 120, 242)'}}>quit</span><span style={{color: 'rgb(56, 58, 66)'}}>()</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>open</span><span style={{color: 'rgb(56, 58, 66)'}}>(sys.</span><span style={{color: 'rgb(228, 86, 73)'}}>path</span><span style={{color: 'rgb(56, 58, 66)'}}>[</span><span style={{color: 'rgb(183, 107, 1)'}}>0</span><span style={{color: 'rgb(56, 58, 66)'}}>] </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"/converted.html"</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>"w"</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># saved as sometimes copy doesn't work correctly</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f.</span><span style={{color: 'rgb(64, 120, 242)'}}>write</span><span style={{color: 'rgb(56, 58, 66)'}}>(html)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f.</span><span style={{color: 'rgb(64, 120, 242)'}}>close</span><span style={{color: 'rgb(56, 58, 66)'}}>()</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>return</span><span style={{color: 'rgb(56, 58, 66)'}}> output</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>formatHTML</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>html</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>html </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> re.</span><span style={{color: 'rgb(64, 120, 242)'}}>sub</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"&lt;pre style=</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>.*?</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>&gt;&lt;code style=</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>.*?</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>&gt;"</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>"&lt;pre class=</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>code</span><span style={{color: 'rgb(80, 161, 79)'}}>\"</span><span style={{color: 'rgb(80, 161, 79)'}}>&gt;&lt;code&gt;"</span><span style={{color: 'rgb(56, 58, 66)'}}>, html) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># remove background</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>open</span><span style={{color: 'rgb(56, 58, 66)'}}>(sys.</span><span style={{color: 'rgb(228, 86, 73)'}}>path</span><span style={{color: 'rgb(56, 58, 66)'}}>[</span><span style={{color: 'rgb(183, 107, 1)'}}>0</span><span style={{color: 'rgb(56, 58, 66)'}}>] </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"/formatted.html"</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>"w"</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># saved as sometimes copy doesn't work correctly</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f.</span><span style={{color: 'rgb(64, 120, 242)'}}>write</span><span style={{color: 'rgb(56, 58, 66)'}}>(html)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>f.</span><span style={{color: 'rgb(64, 120, 242)'}}>close</span><span style={{color: 'rgb(56, 58, 66)'}}>()</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>return</span><span style={{color: 'rgb(56, 58, 66)'}}> html</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> __name__ </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"__main__"</span><span style={{color: 'rgb(56, 58, 66)'}}>:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>len</span><span style={{color: 'rgb(56, 58, 66)'}}>(sys.</span><span style={{color: 'rgb(228, 86, 73)'}}>argv</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(166, 38, 164)'}}>!=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>2</span><span style={{color: 'rgb(56, 58, 66)'}}>:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"fix args"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>else</span><span style={{color: 'rgb(56, 58, 66)'}}>:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>formatted </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>formatHTML</span><span style={{color: 'rgb(56, 58, 66)'}}>(sys.</span><span style={{color: 'rgb(228, 86, 73)'}}>argv</span><span style={{color: 'rgb(56, 58, 66)'}}>[</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>])</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>converted </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>convertHTML</span><span style={{color: 'rgb(56, 58, 66)'}}>(formatted)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>pyperclip.</span><span style={{color: 'rgb(64, 120, 242)'}}>copy</span><span style={{color: 'rgb(56, 58, 66)'}}>(converted)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                    <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"Success"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span>
                </span></code></pre>
            </DropDown><br />
            <p>
                I also modified the code-with-style package further so it runs a custom python script on completion,
                switches themes for you automatically (these are hardcoded sadly), and encoding so that <b>/</b> and other 
                special characters don't break the html output. My modified
                fork can be found <a href="https://github.com/matthewjackswann/copy-with-style">here</a>.
            </p>
        </div>
    );
}
 
export default Component;