import React from "react";
import DropDown from "../../DropDown";
import image0 from "./insaneBolt0.png";
import image1 from "./insaneBolt1.png";
import image2 from "./insaneBolt2.png";

function Component() { 

    return <div>
        <h1>Insane Bolt</h1><br />
        <p>This is one of the miscellaneous challenges in the HTB Uni CTF Qualifiers 2021</p><br />
        <p>We are only given an ip address, a port number and the following description:</p>
        <div className="code" style={{textAlign: "center"}}>
            <code>
            {`This insane scientist wants to craft the most powerful android in the world! Help him collect many 🔩 to achieve his goal. Also, he needs many 💎 to make it even more strong and pwoerful than any other android. Good luck adventurer!`}
            </code>
        </div>
        <p>First I tried connecting to the server using a tool called netcat.</p>
        <div className="code">
            <code>
            {`nc <ip_address> <port>`}
            </code>
        </div>
        <p>This was successful and I received the prompt:</p>
        <img src={image0} alt="a menu screen with options for instructions or to play"/>
        <p>The instructions page looks like:</p>
        <img src={image1} alt="help the robot reach the diamond following the shortest path" />
        <p>And when you choose play:</p>
        <img src={image2} alt="a maze with the robot at the top and a diamond at the bottom" /><br />
        <p>
            When entering the path of the maze if you take too long or are incorrect then the 
            connection is closed.
        </p>
        <p>
            It's a simple case of writing a script that will interact with the server to automatically
            solve the mazes.
        </p><br />
        <p>
            I first wrote a python script that connects to the port and reads off the first maze. I then 
            turns turns the maze into a 2d array which can be searched to solve the maze.
        </p><br />
        <p>
            To solve the maze I decided to use a breadth-first search algorithm, where from the starting
            point in looks at all of the starting points neighbours. It then looks at all of their neighbours
            that haven't already been considered. This continues until the end is found. If the end is not connected
            to the start the maze is impossible and the program exits.
        </p>
        <p>
            To map the path the robot should take at each step of the BFS algorithm, each new position saves which
            neighbour it has come from. This mean that from the end we can look at the step before that, the step
            before the step before that and so on. This continues until we return back to the start.
        </p><br />
        <p>
            All that is required to do now is save this sequence and send it to the server. Then we can receive the 
            next maze and repeat.
        </p><br />
        <p>The full script is below</p><br />
        <DropDown>
            <h4>responder.py <i className="arrow down" style={{float: "right", marginRight: "10px"}} /></h4>
            <pre className="code"><code><span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> socket</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>import</span><span style={{color: 'rgb(56, 58, 66)'}}> sys</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>HOST </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'HOST'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>PORT </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>int</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>'PORT'</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>border </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'🔥'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>wall </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'☠️'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>player </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'🤖'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>path </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'🔩'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>end </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>'💎'</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>findStart</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>grid</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>for</span><span style={{color: 'rgb(56, 58, 66)'}}> x </span><span style={{color: 'rgb(166, 38, 164)'}}>in</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>range</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(1, 132, 188)'}}>len</span><span style={{color: 'rgb(56, 58, 66)'}}>(grid[</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>])): </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># start is always in row 1 of the grid</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> grid[</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>][x] </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> player:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(166, 38, 164)'}}>return</span><span style={{color: 'rgb(56, 58, 66)'}}> (x,</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>checkNeighbor</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>x</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>y</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>parent</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>visited</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>toVisit</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>trace</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>finished</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>neighbour </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> (x, y)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>not</span><span style={{color: 'rgb(56, 58, 66)'}}> neighbour </span><span style={{color: 'rgb(166, 38, 164)'}}>in</span><span style={{color: 'rgb(56, 58, 66)'}}> visited:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>n </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> grid[y][x]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> n </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> path:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>toVisit.</span><span style={{color: 'rgb(64, 120, 242)'}}>append</span><span style={{color: 'rgb(56, 58, 66)'}}>(neighbour)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>visited.</span><span style={{color: 'rgb(64, 120, 242)'}}>append</span><span style={{color: 'rgb(56, 58, 66)'}}>(neighbour)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>trace[neighbour] </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> parent</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> n </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> end:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>toVisit </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> [] </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># quits loop</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>trace[neighbour] </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> parent</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>finished.</span><span style={{color: 'rgb(64, 120, 242)'}}>append</span><span style={{color: 'rgb(56, 58, 66)'}}>(neighbour)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>bfs</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>grid</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(56, 58, 66)'}}>start</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>visited </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> []</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>toVisit </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> [start]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>trace </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> {"{"}{"}"}</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>finished </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> []</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>while</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>len</span><span style={{color: 'rgb(56, 58, 66)'}}>(toVisit) </span><span style={{color: 'rgb(166, 38, 164)'}}>&gt;</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>0</span><span style={{color: 'rgb(56, 58, 66)'}}>:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>x, y </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> toVisit.</span><span style={{color: 'rgb(64, 120, 242)'}}>pop</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>0</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>for</span><span style={{color: 'rgb(56, 58, 66)'}}> dx </span><span style={{color: 'rgb(166, 38, 164)'}}>in</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>range</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(166, 38, 164)'}}>-</span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>,</span><span style={{color: 'rgb(183, 107, 1)'}}>2</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(64, 120, 242)'}}>checkNeighbor</span><span style={{color: 'rgb(56, 58, 66)'}}>(x </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> dx, y, (x, y), visited, toVisit, trace, finished)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(64, 120, 242)'}}>checkNeighbor</span><span style={{color: 'rgb(56, 58, 66)'}}>(x, y </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>, (x, y), visited, toVisit, trace, finished)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>return</span><span style={{color: 'rgb(56, 58, 66)'}}> (trace, finished)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>def</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>removeSpaces</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(56, 58, 66)'}}>s</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>return</span><span style={{color: 'rgb(56, 58, 66)'}}> s.</span><span style={{color: 'rgb(64, 120, 242)'}}>replace</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>" "</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>).</span><span style={{color: 'rgb(64, 120, 242)'}}>replace</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>u"</span><span style={{color: 'rgb(80, 161, 79)'}}>\ufe0f</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>, </span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># removes padding and charater formatting</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}> </span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(166, 38, 164)'}}>with</span><span style={{color: 'rgb(56, 58, 66)'}}> socket.</span><span style={{color: 'rgb(64, 120, 242)'}}>socket</span><span style={{color: 'rgb(56, 58, 66)'}}>(socket.</span><span style={{color: 'rgb(228, 86, 73)'}}>AF_INET</span><span style={{color: 'rgb(56, 58, 66)'}}>, socket.</span><span style={{color: 'rgb(228, 86, 73)'}}>SOCK_STREAM</span><span style={{color: 'rgb(56, 58, 66)'}}>) </span><span style={{color: 'rgb(166, 38, 164)'}}>as</span><span style={{color: 'rgb(56, 58, 66)'}}> s:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>s.</span><span style={{color: 'rgb(64, 120, 242)'}}>connect</span><span style={{color: 'rgb(56, 58, 66)'}}>((HOST, PORT))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># get instructions. these are the same each time but are included for clarity</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>data </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> s.</span><span style={{color: 'rgb(64, 120, 242)'}}>recv</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>1024</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>(), </span><span style={{color: 'rgb(56, 58, 66)'}}>end</span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>s.</span><span style={{color: 'rgb(64, 120, 242)'}}>sendall</span><span style={{color: 'rgb(56, 58, 66)'}}>(str.</span><span style={{color: 'rgb(64, 120, 242)'}}>encode</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"1</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"1"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>data </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> s.</span><span style={{color: 'rgb(64, 120, 242)'}}>recv</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>1024</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># gets first grid from server</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>(), </span><span style={{color: 'rgb(56, 58, 66)'}}>end</span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>s.</span><span style={{color: 'rgb(64, 120, 242)'}}>sendall</span><span style={{color: 'rgb(56, 58, 66)'}}>(str.</span><span style={{color: 'rgb(64, 120, 242)'}}>encode</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"2</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"2"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>data </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> s.</span><span style={{color: 'rgb(64, 120, 242)'}}>recv</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>4096</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>(), </span><span style={{color: 'rgb(56, 58, 66)'}}>end</span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>grid </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>().</span><span style={{color: 'rgb(64, 120, 242)'}}>strip</span><span style={{color: 'rgb(56, 58, 66)'}}>().</span><span style={{color: 'rgb(64, 120, 242)'}}>split</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>)[:</span><span style={{color: 'rgb(166, 38, 164)'}}>-</span><span style={{color: 'rgb(183, 107, 1)'}}>2</span><span style={{color: 'rgb(56, 58, 66)'}}>]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(56, 58, 66)'}}>grid </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>list</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(1, 132, 188)'}}>map</span><span style={{color: 'rgb(56, 58, 66)'}}>(removeSpaces, grid))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"    "}</span><span style={{color: 'rgb(166, 38, 164)'}}>while</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>True</span><span style={{color: 'rgb(56, 58, 66)'}}>: </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># continue looping till an error is thrown</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>start </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>findStart</span><span style={{color: 'rgb(56, 58, 66)'}}>(grid)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>trace, finished </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(64, 120, 242)'}}>bfs</span><span style={{color: 'rgb(56, 58, 66)'}}>(grid, start)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> (</span><span style={{color: 'rgb(1, 132, 188)'}}>len</span><span style={{color: 'rgb(56, 58, 66)'}}>(finished) </span><span style={{color: 'rgb(166, 38, 164)'}}>!=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}>):</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"Shouldn't ever happen"</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>sys.</span><span style={{color: 'rgb(64, 120, 242)'}}>exit</span><span style={{color: 'rgb(56, 58, 66)'}}>()</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>route </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>""</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>currentNode </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> finished[</span><span style={{color: 'rgb(183, 107, 1)'}}>0</span><span style={{color: 'rgb(56, 58, 66)'}}>]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(166, 38, 164)'}}>while</span><span style={{color: 'rgb(56, 58, 66)'}}> currentNode </span><span style={{color: 'rgb(166, 38, 164)'}}>!=</span><span style={{color: 'rgb(56, 58, 66)'}}> start: </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># traces from end to start</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>cx, cy </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> currentNode</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>px, py </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> trace[currentNode] </span><span style={{color: 'rgb(160, 161, 167)', fontStyle: 'italic'}}># parent node</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>direction </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>""</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> px </span><span style={{color: 'rgb(166, 38, 164)'}}>-</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> cx:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"                "}</span><span style={{color: 'rgb(56, 58, 66)'}}>direction </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"L"</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> px </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> cx:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"                "}</span><span style={{color: 'rgb(56, 58, 66)'}}>direction </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"R"</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(166, 38, 164)'}}>if</span><span style={{color: 'rgb(56, 58, 66)'}}> py </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(183, 107, 1)'}}>1</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(166, 38, 164)'}}>==</span><span style={{color: 'rgb(56, 58, 66)'}}> cy:</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"                "}</span><span style={{color: 'rgb(56, 58, 66)'}}>direction </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"D"</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>route </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> direction </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> route</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"            "}</span><span style={{color: 'rgb(56, 58, 66)'}}>currentNode </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> trace[currentNode]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>s.</span><span style={{color: 'rgb(64, 120, 242)'}}>sendall</span><span style={{color: 'rgb(56, 58, 66)'}}>(str.</span><span style={{color: 'rgb(64, 120, 242)'}}>encode</span><span style={{color: 'rgb(56, 58, 66)'}}>(route </span><span style={{color: 'rgb(166, 38, 164)'}}>+</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>))</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(route)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>data </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> s.</span><span style={{color: 'rgb(64, 120, 242)'}}>recv</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(183, 107, 1)'}}>100000</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(1, 132, 188)'}}>print</span><span style={{color: 'rgb(56, 58, 66)'}}>(data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>(), </span><span style={{color: 'rgb(56, 58, 66)'}}>end</span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(80, 161, 79)'}}>""</span><span style={{color: 'rgb(56, 58, 66)'}}>)</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>grid </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> data.</span><span style={{color: 'rgb(64, 120, 242)'}}>decode</span><span style={{color: 'rgb(56, 58, 66)'}}>().</span><span style={{color: 'rgb(64, 120, 242)'}}>strip</span><span style={{color: 'rgb(56, 58, 66)'}}>().</span><span style={{color: 'rgb(64, 120, 242)'}}>split</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(80, 161, 79)'}}>\n</span><span style={{color: 'rgb(80, 161, 79)'}}>"</span><span style={{color: 'rgb(56, 58, 66)'}}>)[</span><span style={{color: 'rgb(183, 107, 1)'}}>3</span><span style={{color: 'rgb(56, 58, 66)'}}>:</span><span style={{color: 'rgb(166, 38, 164)'}}>-</span><span style={{color: 'rgb(183, 107, 1)'}}>2</span><span style={{color: 'rgb(56, 58, 66)'}}>]</span></span>{"\n"}<span style={{display: 'inline-block'}} className="line">
                <span style={{color: 'rgb(56, 58, 66)'}}>{"        "}</span><span style={{color: 'rgb(56, 58, 66)'}}>grid </span><span style={{color: 'rgb(166, 38, 164)'}}>=</span><span style={{color: 'rgb(56, 58, 66)'}}> </span><span style={{color: 'rgb(1, 132, 188)'}}>list</span><span style={{color: 'rgb(56, 58, 66)'}}>(</span><span style={{color: 'rgb(1, 132, 188)'}}>map</span><span style={{color: 'rgb(56, 58, 66)'}}>(removeSpaces, grid))</span>
            </span></code></pre>
        </DropDown>
    </div>
}

export default Component;
